name: Deploy Frontend to Firebase Hosting

on:
    push:
        paths:
            - "frontend/**"
        branches:
            - main # 배포를 트리거할 브랜치

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. 코드 체크아웃
            - name: Checkout repository
              uses: actions/checkout@v3

            # 2. Node.js 설정
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.5.0" # 프로젝트에 맞는 Node.js 버전 설정

            # 3. Node.js 설정 아래에 추가
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                path: frontend/node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-

            # 4. 프론트엔드 의존성 설치 및 빌드
            - name: Install and Build Frontend
              run: |
                  cd frontend
                  npm install
                  CI=false npm run build  # CI=false 설정 추가
              env:
                  CI: false # 환경 변수 덮어쓰기

            # 5. Firebase CLI 설정
            - name: Setup Firebase
              uses: w9jds/firebase-action@v13.29.1
              with:
                  args: deploy --only hosting --debug
                  working-directory: frontend
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
