name: Deploy Backend to App Engine

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main # main 브랜치에 푸시될 때만 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Java 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 캐시 설정 (빌드 속도 향상)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle 빌드 준비: gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./backend/gradlew
        shell: bash

      # 5. application.properties 생성
      - name: Create application.properties
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.properties
        shell: bash

      # 6. application.properties 전달
      - name: Deliver application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
        shell: bash

      # 7. Gradle 빌드
      - name: Build with Gradle
        run: |
          cd backend
          ./gradlew clean build --stacktrace
        shell: bash

      # 8. Google Cloud 인증
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_BACKEND }}

      # 9. Cloud SDK 설정
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: app-engine-java

      # 10. App Engine 배포
      - name: Deploy to App Engine
        run: |
          cd backend
          gcloud app deploy --quiet