name: Deploy Frontend to Firebase Hosting

on:
    push:
        paths:
            - "frontend/**"
        branches:
            - main # 배포를 트리거할 브랜치

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. 코드 체크아웃
            - name: Checkout repository
              uses: actions/checkout@v3

            # 2. Node.js 설정
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "12.0" # 프로젝트에 맞는 Node.js 버전 설정

            # 3. 의존성 설치
            - name: Install dependencies
              run: npm install
              working-directory: ./frontend # 프론트엔드 디렉토리 경로

            # 4. 빌드
            - name: Build frontend
              run: npm run build
              working-directory: ./frontend # 프론트엔드 디렉토리 경로

            # 5. Firebase CLI 설정
            - name: Setup Firebase
              uses: w9jds/firebase-action@v2.2.0
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
